#!/usr/bin/env bash
# Transfers a file from the local client to a remote server

# Check if exactly 4 arguments are provided
if [ "$#" -ne 4 ]; then
	    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	        exit 1
fi

# Assign arguments to variables
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Transfer the file to the remote server home directory
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
EOF
